---
title: "Data Wrangling Final for GitHub"
author: Drew Berkland
format: gfm
execute: 
  warning: false
  message: false
  errors: false
---

## File Uploads

```{python}
import pandas as pd
data= pd.read_csv("C:/Users/drewb/Downloads/MLB_Player_Data.csv")
```

## Question 1: How do performance statistics compare between HOFers and Non HOFers?


```{python}
data['HOF Status'] = data['HOF Status'].astype(str).str.lower()

data['HOF Status'] = data['HOF Status'].apply(lambda x: 1 if x in ['true'] else 0)

numeric_cols = data.select_dtypes(include='number').columns.tolist()

hof_compare = data.groupby('HOF Status')[numeric_cols].mean()

hof_compare
```

First, I cleaned the binary HOF Status column to make sure all of the T/F values were lowercase. Then, I used the lambda function to assign numeric values (1 or 0) to the HOF Status column. A player with HOF Status = 1 is a HOFer. From there, I was able to run the mean of each numeric column to compare the performance statistics between HOfer and Non HOFer 

Now, I will vizualize these stats using a for loop that iterates through each numeric stat, creating a box plot for each one. This will further respond to the question I posed.

```{python}
import seaborn as sns
import matplotlib.pyplot as plt

numeric_stats = data.select_dtypes(include="number").columns

for stat in numeric_stats:
    plt.figure(figsize=(6, 4))
    sns.boxplot(data=data, x="HOF Status", y=stat)
    plt.title(f"HOF vs Non-HOF: {stat}")
    plt.xlabel("HOF Status")
    plt.ylabel(stat)
    plt.tight_layout()
    plt.show()
```

The box plots clearly show that key statistics such as WAR, BA, WAA, OPS, SLG are significantly higher amongst HOFers. This is to be expected, but it shows that each statistical categroy is much higher. One thing that jumps out to me is the amount of games played between HOFers and Non HOFers. HOFers have more longevity in the game which allows them more time to post their high statistics. This is shown through the aggregated mean code block and the box plot for loop. 

## Question 2: How can we look at WAR to predict HOF Status?

WAR is a big statistic used in the MLB today. I wanted to run a model to show how it affects HOF status. I first did this through bootstrap sampling.


```{python}
import numpy as np
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt

bootstrap_samples = 100
t_values = []

for i in range(bootstrap_samples):
    sample = data.sample(frac=1, replace=True)
    model = sm.formula.ols(f'Q("WAR") ~ Q("HOF Status")', data=sample).fit()
    t_val = model.tvalues['Q("HOF Status")']
    t_values.append(t_val)

sns.histplot(t_values)
plt.title("Bootstrap t-values for HOF Status effect on WAR")
plt.show()

```

The bootstrap tvalues model shows that a player's WAR is signifcant in predicting whether they will make the HOF or not. This means looking at WAR is highly reliable in determinig HOF Status.

Next, I wanted to see the magnitude, direction, and p-value significance of WAR on HOF Status. I ran a simple regression here.

```{python}
import statsmodels.formula.api as smf

regression = smf.ols("WAR ~ Q('HOF Status')", data=data).fit()
regression.summary()
```

 Hall of Famers average roughly 55 more WAR than non-HOF players, meaning WAR is a separator between the groups. The model explains about 38% of the variation in career WAR shown by R- Squared. The p-value is below .05 indicating a significant relationship. 

 One thing to note here is that while this variable is significant and his positive direction, the lower r-squared means that there are other strong predictors of HOF status outside of WAR.

## Question 3: How does batting average differ by decade and HOF Status?

In baseball, there are arguments that hitters are focusing less on average and more on power. Therefore, power numbers (SLG) are up and average numbers are down. I wanted to test this theory and see the trend between the two classes I made earlier of HOFer and non HOFer.

```{python}

data['decade'] = (data['Last Season'] // 10) * 10

ba_pivot = data.pivot_table(index='decade',columns='HOF Status', values='BA', aggfunc='mean')

print(ba_pivot)
```

Here, I had to make a 'decade' column using a floor division operator to get what decade the players' last seasone was in. From there, I could pivot each decade, organize by HOF Status, and have BA appear in the values. 

The numbers here kind of debunked the theory that batting average is trending down over time. This was surprising to me. This could be due to sample size of the dataset, but interesting nontheless.
